import { Product } from '@/types/Product';
import { ProductCategory } from '@/types/ProductCategory';

// eslint-disable-next-line import/prefer-default-export
export const products: Product[] = [
	{
		id: 111,
		name: 'PerfectAire - ScentAire',
		description: '100% Essential Oil - Tea Tree Oil - 10ml',
		image:
			'https://media.takealot.com/covers_tsins/68704043/68704043-1-pdpxl.jpeg',
		currentPrice: 387,
		oldPrice: 894,
		rating: 4,
		numberOfVotes: 90,
		categories: ['Gardening'],
		vendor: 'CMK',
		isInStock: true,
	},
	{
		id: 112,
		name: 'Greenleaf Forest Ultrasonic Essential Oil',
		description:
			'Not only do they add a beautiful aroma into the air but they also humidify the air.',
		image:
			'https://media.takealot.com/covers_tsins/62253629/62253629-1-pdpxl.jpeg',
		currentPrice: 647,
		oldPrice: 994,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Eco', 'Natural'],
		vendor: 'Cougar',
		isInStock: false,
	},
	{
		id: 113,
		name: 'Hanging Plants',
		description: 'Artificial Plant',
		image:
			'https://media.takealot.com/covers_images/d513cbb80859489b8fed8e982987a770/s-zoom.file',
		currentPrice: 547,
		oldPrice: 494,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Home ]and Decorate'],
		vendor: 'KMB',
		isInStock: false,
	},
	{
		id: 114,
		name: 'HouzeComfort Artificial Ficus Indoor and Outdoor Pot Plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/7b16abb1f3574dc8bc25ee3dcbf8875a/s-pdpxl.file',
		currentPrice: 847,
		oldPrice: 1494,
		rating: 1,
		numberOfVotes: 1,
		categories: ['Gardening'],
		vendor: 'WBx',
		isInStock: true,
	},
	{
		id: 115,
		name: 'Artificial monsteria plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/4aac18fd41e44329b9f5b2765d8c558e/s-pdpxl.file',
		currentPrice: 347,
		oldPrice: 694,
		rating: 3,
		numberOfVotes: 70,
		categories: ['Gardening'],
		vendor: 'Crazee Sales',
		isInStock: true,
	},
	{
		id: 116,
		name: 'PerfectAire - ScentAire',
		description: '100% Essential Oil - Tea Tree Oil - 10ml',
		image:
			'https://media.takealot.com/covers_tsins/68704043/68704043-1-pdpxl.jpeg',
		currentPrice: 387,
		oldPrice: 894,
		rating: 4,
		numberOfVotes: 90,
		categories: ['Gardening'],
		vendor: 'CMK',
		isInStock: true,
	},
	{
		id: 11234,
		name: 'Greenleaf Forest Ultrasonic Essential Oil',
		description:
			'Not only do they add a beautiful aroma into the air but they also humidify the air.',
		image:
			'https://media.takealot.com/covers_tsins/62253629/62253629-1-pdpxl.jpeg',
		currentPrice: 647,
		oldPrice: 994,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: false,
	},
	{
		id: 15213,
		name: 'Hanging Plants',
		description: 'Artificial Plant',
		image:
			'https://media.takealot.com/covers_images/d513cbb80859489b8fed8e982987a770/s-zoom.file',
		currentPrice: 547,
		oldPrice: 494,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'Eco services',
		isInStock: true,
	},
	{
		id: 1825414,
		name: 'HouzeComfort Artificial Ficus Indoor and Outdoor Pot Plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/7b16abb1f3574dc8bc25ee3dcbf8875a/s-pdpxl.file',
		currentPrice: 847,
		oldPrice: 1494,
		rating: 1,
		numberOfVotes: 1,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 110755,
		name: 'Artificial monsteria plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/4aac18fd41e44329b9f5b2765d8c558e/s-pdpxl.file',
		currentPrice: 347,
		oldPrice: 694,
		rating: 3,
		numberOfVotes: 70,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 114731,
		name: 'PerfectAire - ScentAire',
		description: '100% Essential Oil - Tea Tree Oil - 10ml',
		image:
			'https://media.takealot.com/covers_tsins/68704043/68704043-1-pdpxl.jpeg',
		currentPrice: 387,
		oldPrice: 894,
		rating: 4,
		numberOfVotes: 90,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 115555555732,
		name: 'Greenleaf Forest Ultrasonic Essential Oil',
		description:
			'Not only do they add a beautiful aroma into the air but they also humidify the air.',
		image:
			'https://media.takealot.com/covers_tsins/62253629/62253629-1-pdpxl.jpeg',
		currentPrice: 647,
		oldPrice: 994,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'CMK',
		isInStock: true,
	},
	{
		id: 1186798563,
		name: 'Hanging Plants',
		description: 'Artificial Plant',
		image:
			'https://media.takealot.com/covers_images/d513cbb80859489b8fed8e982987a770/s-zoom.file',
		currentPrice: 547,
		oldPrice: 494,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 116374,
		name: 'HouzeComfort Artificial Ficus Indoor and Outdoor Pot Plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/7b16abb1f3574dc8bc25ee3dcbf8875a/s-pdpxl.file',
		currentPrice: 847,
		oldPrice: 1494,
		rating: 1,
		numberOfVotes: 1,
		categories: ['Gardening'],
		vendor: 'CMK',
		isInStock: true,
	},
	{
		id: 1157439670,
		name: 'Artificial monsteria plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/4aac18fd41e44329b9f5b2765d8c558e/s-pdpxl.file',
		currentPrice: 347,
		oldPrice: 694,
		rating: 3,
		numberOfVotes: 70,
		categories: ['Gardening'],
		vendor: 'Cougar',
		isInStock: true,
	},
	{
		id: 11657681,
		name: 'PerfectAire - ScentAire',
		description: '100% Essential Oil - Tea Tree Oil - 10ml',
		image:
			'https://media.takealot.com/covers_tsins/68704043/68704043-1-pdpxl.jpeg',
		currentPrice: 387,
		oldPrice: 894,
		rating: 4,
		numberOfVotes: 90,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 119875,
		name: 'Greenleaf Forest Ultrasonic Essential Oil',
		description:
			'Not only do they add a beautiful aroma into the air but they also humidify the air.',
		image:
			'https://media.takealot.com/covers_tsins/62253629/62253629-1-pdpxl.jpeg',
		currentPrice: 647,
		oldPrice: 994,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 113637675879,
		name: 'Hanging Plants',
		description: 'Artificial Plant',
		image:
			'https://media.takealot.com/covers_images/d513cbb80859489b8fed8e982987a770/s-zoom.file',
		currentPrice: 547,
		oldPrice: 494,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'Crazee Style',
		isInStock: true,
	},
	{
		id: 114654875497,
		name: 'HouzeComfort Artificial Ficus Indoor and Outdoor Pot Plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/7b16abb1f3574dc8bc25ee3dcbf8875a/s-pdpxl.file',
		currentPrice: 847,
		oldPrice: 1494,
		rating: 1,
		numberOfVotes: 1,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 1167895,
		name: 'Artificial monsteria plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/4aac18fd41e44329b9f5b2765d8c558e/s-pdpxl.file',
		currentPrice: 347,
		oldPrice: 694,
		rating: 3,
		numberOfVotes: 70,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 11497091,
		name: 'PerfectAire - ScentAire',
		description: '100% Essential Oil - Tea Tree Oil - 10ml',
		image:
			'https://media.takealot.com/covers_tsins/68704043/68704043-1-pdpxl.jpeg',
		currentPrice: 387,
		oldPrice: 894,
		rating: 4,
		numberOfVotes: 90,
		categories: ['Gardening'],
		vendor: 'CMK',
		isInStock: true,
	},
	{
		id: 1160934462,
		name: 'Greenleaf Forest Ultrasonic Essential Oil',
		description:
			'Not only do they add a beautiful aroma into the air but they also humidify the air.',
		image:
			'https://media.takealot.com/covers_tsins/62253629/62253629-1-pdpxl.jpeg',
		currentPrice: 647,
		oldPrice: 994,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
	{
		id: 117569703,
		name: 'Hanging Plants',
		description: 'Artificial Plant',
		image:
			'https://media.takealot.com/covers_images/d513cbb80859489b8fed8e982987a770/s-zoom.file',
		currentPrice: 547,
		oldPrice: 494,
		rating: 5,
		numberOfVotes: 10,
		categories: ['Gardening'],
		vendor: 'Cougar',
		isInStock: true,
	},
	{
		id: 113276474,
		name: 'HouzeComfort Artificial Ficus Indoor and Outdoor Pot Plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/7b16abb1f3574dc8bc25ee3dcbf8875a/s-pdpxl.file',
		currentPrice: 847,
		oldPrice: 1494,
		rating: 1,
		numberOfVotes: 1,
		categories: ['Gardening'],
		vendor: 'CMK',
		isInStock: true,
	},
	{
		id: 1198745635,
		name: 'Artificial monsteria plant',
		description: 'Decorate and Style with Plants',
		image:
			'https://media.takealot.com/covers_images/4aac18fd41e44329b9f5b2765d8c558e/s-pdpxl.file',
		currentPrice: 347,
		oldPrice: 694,
		rating: 3,
		numberOfVotes: 70,
		categories: ['Gardening'],
		vendor: 'Eaglestack',
		isInStock: true,
	},
];

export const productCategories: ProductCategory[] = [
	{
		id: 14,
		name: 'Groceries',
	},
];
